/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator_roundbutton;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
        
/**
 *
 * @author Shahidkhan
 */
public class Calculator_RoundButtons extends javax.swing.JFrame {

    double firstnum;
    double secondnum;
    double result;
    String operations;
    
    /**
     * Creates new form Calculator_RoundButtons
     */
    public Calculator_RoundButtons() {
        initComponents();
          setTitle("Calculator");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txField = new javax.swing.JTextField();
        btn_divsion = new javax.swing.JButton();
        back = new javax.swing.JButton();
        btn_C = new javax.swing.JButton();
        btn_eight = new javax.swing.JButton();
        btn_seven = new javax.swing.JButton();
        btn_negative = new javax.swing.JButton();
        btn_nine = new javax.swing.JButton();
        btn_five = new javax.swing.JButton();
        btn_four = new javax.swing.JButton();
        btn_plus = new javax.swing.JButton();
        btn_six = new javax.swing.JButton();
        btn_two = new javax.swing.JButton();
        btn_one = new javax.swing.JButton();
        btn_multiply = new javax.swing.JButton();
        btn_three = new javax.swing.JButton();
        btn_dot = new javax.swing.JButton();
        btn_zero = new javax.swing.JButton();
        btn_Equal = new javax.swing.JButton();
        btn_plus_div_min = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldActionPerformed(evt);
            }
        });
        getContentPane().add(txField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 312, 47));

        btn_divsion.setBackground(new java.awt.Color(0, 102, 102));
        btn_divsion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_divsion.setText("/");
        btn_divsion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divsionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_divsion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 70, 61));

        back.setBackground(new java.awt.Color(255, 102, 51));
        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setText("bac");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 61));

        btn_C.setBackground(new java.awt.Color(255, 102, 51));
        btn_C.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_C.setText("C");
        btn_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CActionPerformed(evt);
            }
        });
        getContentPane().add(btn_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 150, 61));

        btn_eight.setBackground(new java.awt.Color(51, 153, 0));
        btn_eight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_eight.setText("8");
        btn_eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eightActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 70, 61));

        btn_seven.setBackground(new java.awt.Color(51, 153, 0));
        btn_seven.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_seven.setText("7");
        btn_seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sevenActionPerformed(evt);
            }
        });
        getContentPane().add(btn_seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, 61));

        btn_negative.setBackground(new java.awt.Color(0, 102, 102));
        btn_negative.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_negative.setText("-");
        btn_negative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_negativeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_negative, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 70, 61));

        btn_nine.setBackground(new java.awt.Color(51, 153, 0));
        btn_nine.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_nine.setText("9");
        btn_nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nineActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 70, 61));

        btn_five.setBackground(new java.awt.Color(51, 153, 0));
        btn_five.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_five.setText("5");
        btn_five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fiveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_five, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 70, 61));

        btn_four.setBackground(new java.awt.Color(51, 153, 0));
        btn_four.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_four.setText("4");
        btn_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fourActionPerformed(evt);
            }
        });
        getContentPane().add(btn_four, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 70, 61));

        btn_plus.setBackground(new java.awt.Color(0, 102, 102));
        btn_plus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_plus.setText("+");
        btn_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_plusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 70, 61));

        btn_six.setBackground(new java.awt.Color(51, 153, 0));
        btn_six.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_six.setText("6");
        btn_six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sixActionPerformed(evt);
            }
        });
        getContentPane().add(btn_six, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 70, 61));

        btn_two.setBackground(new java.awt.Color(51, 153, 0));
        btn_two.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_two.setText("2");
        btn_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_twoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_two, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 70, 61));

        btn_one.setBackground(new java.awt.Color(51, 153, 0));
        btn_one.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_one.setText("1");
        btn_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oneActionPerformed(evt);
            }
        });
        getContentPane().add(btn_one, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 70, 61));

        btn_multiply.setBackground(new java.awt.Color(0, 102, 102));
        btn_multiply.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_multiply.setText("*");
        btn_multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplyActionPerformed(evt);
            }
        });
        getContentPane().add(btn_multiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 70, 61));

        btn_three.setBackground(new java.awt.Color(51, 153, 0));
        btn_three.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_three.setText("3");
        btn_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_threeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_three, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 70, 61));

        btn_dot.setBackground(new java.awt.Color(51, 153, 0));
        btn_dot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_dot.setText(".");
        btn_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dotActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dot, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 70, 61));

        btn_zero.setBackground(new java.awt.Color(51, 153, 0));
        btn_zero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_zero.setText("0");
        btn_zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zeroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 70, 61));

        btn_Equal.setBackground(new java.awt.Color(0, 102, 102));
        btn_Equal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Equal.setText("=");
        btn_Equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EqualActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Equal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 70, 61));

        btn_plus_div_min.setBackground(new java.awt.Color(51, 153, 0));
        btn_plus_div_min.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_plus_div_min.setText("+/-");
        btn_plus_div_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_plus_div_minActionPerformed(evt);
            }
        });
        getContentPane().add(btn_plus_div_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 70, 61));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldActionPerformed

    private void btn_sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sevenActionPerformed
        // TODO add your handling code here:
        String EnterNumber = txField.getText();
        if(EnterNumber == "")
        {
            txField.setText(btn_seven.getText());
        }
        else
        {
            EnterNumber=txField.getText()+ btn_seven.getText();
            txField.setText(EnterNumber);
        }
    }//GEN-LAST:event_btn_sevenActionPerformed

    private void btn_eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eightActionPerformed
        // TODO add your handling code here:
        String EnterNumber = txField.getText();
        if(EnterNumber == "")
        {
            txField.setText(btn_eight.getText());
        }
        else
        {
            EnterNumber=txField.getText()+ btn_eight.getText();
            txField.setText(EnterNumber);
        }
    }//GEN-LAST:event_btn_eightActionPerformed

    private void btn_nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nineActionPerformed
        // TODO add your handling code here:
        String EnterNumber = txField.getText();
        if(EnterNumber == "")
        {
            txField.setText(btn_nine.getText());
        }
        else
        {
            EnterNumber=txField.getText()+ btn_nine.getText();
            txField.setText(EnterNumber);
        }
    }//GEN-LAST:event_btn_nineActionPerformed

    private void btn_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fourActionPerformed
        // TODO add your handling code here:
        String EnterNumber = txField.getText();
        if(EnterNumber == "")
        {
            txField.setText(btn_four.getText());
        }
        else
        {
            EnterNumber=txField.getText()+ btn_four.getText();
            txField.setText(EnterNumber);
        }
    }//GEN-LAST:event_btn_fourActionPerformed

    private void btn_fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fiveActionPerformed
        // TODO add your handling code here:
        String EnterNumber = txField.getText();
        if(EnterNumber == "")
        {
            txField.setText(btn_five.getText());
        }
        else
        {
            EnterNumber=txField.getText()+ btn_five.getText();
            txField.setText(EnterNumber);
        }
    }//GEN-LAST:event_btn_fiveActionPerformed

    private void btn_sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sixActionPerformed
        // TODO add your handling code here:
        String EnterNumber = txField.getText();
        if(EnterNumber == "")
        {
            txField.setText(btn_six.getText());
        }
        else
        {
            EnterNumber=txField.getText()+ btn_six.getText();
            txField.setText(EnterNumber);
        }
    }//GEN-LAST:event_btn_sixActionPerformed

    private void btn_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oneActionPerformed
        // TODO add your handling code here:
        String EnterNumber = txField.getText();
        if(EnterNumber == "")
        {
            txField.setText(btn_one.getText());
        }
        else
        {
            EnterNumber=txField.getText()+ btn_one.getText();
            txField.setText(EnterNumber);
        }
    }//GEN-LAST:event_btn_oneActionPerformed

    private void btn_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_twoActionPerformed
        // TODO add your handling code here:
        String EnterNumber = txField.getText();
        if(EnterNumber == "")
        {
            txField.setText(btn_two.getText());
        }
        else
        {
            EnterNumber=txField.getText()+ btn_two.getText();
            txField.setText(EnterNumber);
        }
    }//GEN-LAST:event_btn_twoActionPerformed

    private void btn_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_threeActionPerformed
        // TODO add your handling code here:
        String EnterNumber = txField.getText();
        if(EnterNumber == "")
        {
            txField.setText(btn_three.getText());
        }
        else
        {
            EnterNumber=txField.getText()+ btn_three.getText();
            txField.setText(EnterNumber);
        }
    }//GEN-LAST:event_btn_threeActionPerformed

    private void btn_zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zeroActionPerformed
        // TODO add your handling code here:
        String EnterNumber = txField.getText();
        if(EnterNumber == "")
        {
            txField.setText(btn_zero.getText());
        }
        else
        {
            EnterNumber=txField.getText()+ btn_zero.getText();
            txField.setText(EnterNumber);
        }
    }//GEN-LAST:event_btn_zeroActionPerformed

    private void btn_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dotActionPerformed
        // TODO add your handling code here:
        if(!txField.getText().contains(" "))
        {
            txField.setText(txField.getText()+btn_dot.getText());
        }
    }//GEN-LAST:event_btn_dotActionPerformed

    private void btn_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CActionPerformed
        // TODO add your handling code here:
        txField.setText(" ");
    }//GEN-LAST:event_btn_CActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        String backspace=null;
        if(txField.getText().length() > 0)
        {
            StringBuffer strB= new StringBuffer(txField.getText());
            strB.deleteCharAt(txField.getText().length()-1);
            backspace=strB.toString();
            txField.setText(backspace);
            
        }
    }//GEN-LAST:event_backActionPerformed

    private void btn_divsionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divsionActionPerformed
        // TODO add your handling code here:
        firstnum=Double.parseDouble(txField.getText());
        txField.setText("");
        operations="/";
    }//GEN-LAST:event_btn_divsionActionPerformed

    private void btn_negativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_negativeActionPerformed
        // TODO add your handling code here:
         firstnum=Double.parseDouble(txField.getText());
        txField.setText("");
        operations="-";
    }//GEN-LAST:event_btn_negativeActionPerformed

    private void btn_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_plusActionPerformed
        // TODO add your handling code here:
         firstnum=Double.parseDouble(txField.getText());
        txField.setText("");
        operations="+";
    }//GEN-LAST:event_btn_plusActionPerformed


    private void btn_multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplyActionPerformed
        // TODO add your handling code here:
         firstnum=Double.parseDouble(txField.getText());
        txField.setText("");
        operations="*";
    }//GEN-LAST:event_btn_multiplyActionPerformed

    private void btn_EqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EqualActionPerformed
        // TODO add your handling code here:
        String answer;
        secondnum= Double.parseDouble(txField.getText());
        if(operations=="+")
        {
            result=firstnum+secondnum;
            answer=String.format("%.2f", result);
            txField.setText(answer);
        }
        else if(operations=="-")
        {
            result=firstnum - secondnum;
            answer=String.format("%.2f", result);
            txField.setText(answer);
        }
        else if(operations=="/")
        {
            result=firstnum / secondnum;
            answer=String.format("%.2f", result);
            txField.setText(answer);
        }
        else if(operations=="*")
        {
            result=firstnum * secondnum;
            answer=String.format("%.2f", result);
            txField.setText(answer);
        }
        
        
        
    }//GEN-LAST:event_btn_EqualActionPerformed

    private void btn_plus_div_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_plus_div_minActionPerformed
        // TODO add your handling code here:
        double ops=Double.parseDouble(String.valueOf(txField.getText()));
        ops=ops* (-1);
        txField.setText(String.valueOf(ops));
        
    }//GEN-LAST:event_btn_plus_div_minActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException,
            UnsupportedLookAndFeelException 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator_RoundButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator_RoundButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator_RoundButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator_RoundButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator_RoundButtons().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btn_C;
    private javax.swing.JButton btn_Equal;
    private javax.swing.JButton btn_divsion;
    private javax.swing.JButton btn_dot;
    private javax.swing.JButton btn_eight;
    private javax.swing.JButton btn_five;
    private javax.swing.JButton btn_four;
    private javax.swing.JButton btn_multiply;
    private javax.swing.JButton btn_negative;
    private javax.swing.JButton btn_nine;
    private javax.swing.JButton btn_one;
    private javax.swing.JButton btn_plus;
    private javax.swing.JButton btn_plus_div_min;
    private javax.swing.JButton btn_seven;
    private javax.swing.JButton btn_six;
    private javax.swing.JButton btn_three;
    private javax.swing.JButton btn_two;
    private javax.swing.JButton btn_zero;
    private javax.swing.JTextField txField;
    // End of variables declaration//GEN-END:variables
}
